Repository ajitesh123/auto-review-ai, pull requests merged in 2024-10, with the labels that each got.

#140 DO NOT MERGE - frontend update
  frontend/.prettierignore
  frontend/next.config.js
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/app/globals.css
  frontend/src/app/home/AppIntro.tsx
  frontend/src/app/home/AudioInput.tsx
  frontend/src/app/home/PerformanceReview.tsx
  frontend/src/app/home/ReviewResults.tsx
  frontend/src/app/home/SelfReview.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/assets/icons/mic.svg
  frontend/src/assets/icons/pause.svg
  frontend/src/assets/icons/play.svg
  frontend/src/assets/icons/spinner.svg
  frontend/src/assets/icons/stop.svg
  frontend/src/components/Footer.tsx
  frontend/src/components/GradientBackground.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/ui/button/base-button.tsx
  frontend/src/components/ui/button/index.ts
  frontend/src/components/ui/button/text-button.tsx
  frontend/src/components/ui/spinner/index.ts
  frontend/src/components/ui/spinner/spinner.tsx
  frontend/src/components/ui/svg-icon/index.ts
  frontend/src/components/ui/svg-icon/svg-icon.tsx
  frontend/src/components/ui/switch/index.ts
  frontend/src/components/ui/switch/switch.tsx
  frontend/src/constants/common.js
  frontend/src/constants/links.js
  frontend/src/constants/media.js
  frontend/src/contexts/AppContext.tsx
  frontend/src/utils/classnames/classnames.ts
  frontend/src/utils/classnames/index.ts
  frontend/src/utils/object/index.ts
  frontend/src/utils/object/object.ts
  frontend/tailwind.config.ts
  frontend/tsconfig.json
Labels: enhancement, Dependencies, Review effort [1-5]: 4

#141 Feat/v2
  backend/app_fastapi.py
  backend/app_fastapi_v2.py
  backend/kindle_auth.py
  backend/supabase_client.py
  backend/tests/app_fastapi_v2.py
  requirements.txt
Labels: enhancement, Tests, Error Handling

#142 fixed the port
  Dockerfile
Labels: bug fix

#145 Auth flow, Profile Dropdown, Flash messages setup
  backend/app_fastapi_v2.py
  backend/config.py
  frontend/src/app/globals.css
  frontend/src/app/home/AudioInput.tsx
  frontend/src/app/home/PerformanceReview.tsx
  frontend/src/app/home/SelfReview.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/login/callback/page.tsx
  frontend/src/app/logout/callback/page.tsx
  frontend/src/assets/icons/check-circle.svg
  frontend/src/assets/icons/close.svg
  frontend/src/assets/icons/exclamation-circle.svg
  frontend/src/assets/icons/information-circle.svg
  frontend/src/assets/icons/logout.svg
  frontend/src/assets/icons/price.svg
  frontend/src/assets/icons/x-circle.svg
  frontend/src/components/Header.tsx
  frontend/src/components/Profile.tsx
  frontend/src/components/ui/button/icon-button.tsx
  frontend/src/components/ui/button/index.ts
  frontend/src/components/ui/flash-messages/flash-message.tsx
  frontend/src/components/ui/flash-messages/flash-messages.context.tsx
  frontend/src/components/ui/flash-messages/flash-messages.tsx
  frontend/src/components/ui/flash-messages/index.ts
  frontend/src/components/ui/flash-messages/use-flash-message.ts
  frontend/src/contexts/AppContext.tsx
  frontend/src/services/auth.ts
  frontend/src/services/axiosInstance.ts
  frontend/src/types/user.d.ts
  frontend/tailwind.config.ts
  frontend/tsconfig.json
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#146 Feat/v2
  backend/app_fastapi.py
  backend/app_fastapi_v1.py
  backend/app_fastapi_v2.py
  backend/config.py
  backend/db/connection.py
  backend/db/operations.py
  backend/models/user.py
  backend/supabase_client.py
  backend/tests/app_fastapi_v2.py
  backend/tests/test_data/test_review_data.py
  backend/tests/test_db_operations.py
  pytest.ini
  requirements.txt
Labels: enhancement, Review effort [1-5]: 4, Tests
