Repository ajitesh123/auto-review-ai, pull requests merged in 2024-12, with the labels that each got.

#162 Review layout changes
  frontend/src/app/about/page.tsx
  frontend/src/app/billing/components/BillingAlerts.tsx
  frontend/src/app/billing/components/CurrentPlanDetails.tsx
  frontend/src/app/billing/page.tsx
  frontend/src/app/globals.css
  frontend/src/app/home/AppIntro.tsx
  frontend/src/app/home/HowItWorks.tsx
  frontend/src/app/home/Review.tsx
  frontend/src/app/home/Testimonials.tsx
  frontend/src/app/home/components/AudioInput.tsx
  frontend/src/app/home/components/PerformanceReview.tsx
  frontend/src/app/home/components/ReviewResults.tsx
  frontend/src/app/home/components/SelfReview.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/assets/images/testimonials/jinal_dalal.jpeg
  frontend/src/assets/images/testimonials/thomas_nguyen.jpg
  frontend/src/components/GradientBackground.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Pricing.tsx
  frontend/src/components/TestimonialCard.tsx
  frontend/src/components/ui/badge/badge.tsx
  frontend/src/constants/billing.ts
  frontend/src/services/billing.ts
  frontend/src/services/user.ts
  frontend/src/types/images.d.ts
  frontend/src/types/user.d.ts
Labels: Review effort [1-5]: 4, Minor Change, size:L

#160 Feat/UI play
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/app/about/page.tsx
  frontend/src/app/billing/components/BillingAlerts.tsx
  frontend/src/app/billing/components/CurrentPlanDetails.tsx
  frontend/src/app/billing/page.tsx
  frontend/src/app/globals.css
  frontend/src/app/home/AppIntro.tsx
  frontend/src/app/home/HowItWorks.tsx
  frontend/src/app/home/Review.tsx
  frontend/src/app/home/Testimonials.tsx
  frontend/src/app/home/components/AudioInput.tsx
  frontend/src/app/home/components/PerformanceReview.tsx
  frontend/src/app/home/components/ReviewResults.tsx
  frontend/src/app/home/components/SelfReview.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/assets/icons/background.png
  frontend/src/assets/icons/background2.png
  frontend/src/assets/icons/logo.svg
  frontend/src/assets/images/testimonials/anmol_sinha.png
  frontend/src/assets/images/testimonials/avinash_malik.jpeg
  frontend/src/assets/images/testimonials/jinal_dalal.jpeg
  frontend/src/assets/images/testimonials/kunal_mishra.jpeg
  frontend/src/assets/images/testimonials/kushal_poddar.jpeg
  frontend/src/assets/images/testimonials/mayank_raj.jpeg
  frontend/src/assets/images/testimonials/shan_s.jpeg
  frontend/src/assets/images/testimonials/thomas_nguyen.jpg
  frontend/src/components/GradientBackground.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Pricing.tsx
  frontend/src/components/TestimonialCard.tsx
  frontend/src/components/ui/badge/badge.tsx
  frontend/src/constants/billing.ts
  frontend/src/services/billing.ts
  frontend/src/services/user.ts
  frontend/src/types/images.d.ts
  frontend/src/types/user.d.ts
  public/favicon.ico
Labels: enhancement, Review effort [1-5]: 2, size:XL

#165 priv and terms ui added
  frontend/package-lock.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/app/globals.css
  frontend/src/app/home/AppIntro.tsx
  frontend/src/app/home/Faqs.tsx
  frontend/src/app/home/components/PerformanceReview.tsx
  frontend/src/app/privacy-policy/page.tsx
  frontend/src/app/terms-and-conditions/page.tsx
  frontend/src/assets/icons/logout.svg
  frontend/src/assets/icons/spinner.svg
  frontend/src/components/CustomMarkdown.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/Pricing.tsx
  frontend/src/constants/links.js
  frontend/tailwind.config.ts
Labels: enhancement, Review effort [1-5]: 3, size:L

#164 UI Improvements
  backend/llm.py
  frontend/package-lock.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/app/globals.css
  frontend/src/app/home/AppIntro.tsx
  frontend/src/app/home/Faqs.tsx
  frontend/src/app/home/Testimonials.tsx
  frontend/src/app/home/components/PerformanceReview.tsx
  frontend/src/app/home/components/ReviewResults.tsx
  frontend/src/app/page.tsx
  frontend/src/app/privacy-policy/page.tsx
  frontend/src/app/terms-and-conditions/page.tsx
  frontend/src/assets/icons/close.svg
  frontend/src/components/CustomMarkdown.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/Pricing.tsx
  frontend/src/constants/links.js
  frontend/tailwind.config.ts
Labels: enhancement, Review effort [1-5]: 2, size:XL

#166 Improvements
  backend/app_fastapi_v2.py
  frontend/src/app/billing/page.tsx
  frontend/src/app/home/Review.tsx
  frontend/src/app/home/Testimonials.tsx
  frontend/src/app/home/components/PerformanceReview.tsx
  frontend/src/app/home/components/ReviewResults.tsx
  frontend/src/app/home/components/SelfReview.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/privacy-policy/page.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/Typewriter.tsx
Labels: Minor Change, Review effort [1-5]: 1, size:L

#167 github icon
  frontend/src/assets/icons/github-logo.svg
  frontend/src/components/Header.tsx
  frontend/src/constants/links.js
Labels: Minor Change, size:S

#168 Feat/readme
  README.md
Labels: size:M

#170 fixed bug in intializing new users to have 3 credits
  backend/app_fastapi_v2.py
Labels: size:XS

#171 upgraded model for free user to gemni latest version
  backend/llm.py
  requirements.txt
Labels: size:XS
