Repository ajitesh123/auto-review-ai, pull requests merged in 2024-11, with the labels that each got.

#154 feat: login check on billing
  frontend/src/app/about/page.tsx
  frontend/src/app/billing/components/BillingAlerts.tsx
  frontend/src/app/billing/components/CurrentPlanDetails.tsx
  frontend/src/app/billing/page.tsx
  frontend/src/app/login/callback/page.tsx
  frontend/src/app/logout/callback/page.tsx
  frontend/src/components/Pricing.tsx
  frontend/src/components/ui/badge/badge.tsx
  frontend/src/components/ui/badge/index.ts
  frontend/src/constants/billing.ts
  frontend/src/hooks/useStripeCheckout.tsx
  frontend/src/services/billing.ts
  frontend/src/services/user.ts
  frontend/src/types/user.d.ts
Labels: enhancement, Review effort [1-5]: 3, size:XL

#148 [DNM] pricing ui
  backend/app_fastapi_v2.py
  backend/config.py
  backend/db/operations.py
  backend/middleware/check_auth.py
  backend/models/user.py
  backend/routers/billing.py
  backend/schemas/billing.py
  backend/schemas/review.py
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/app/AuthWrapper.tsx
  frontend/src/app/about/page.tsx
  frontend/src/app/billing/components/BillingAlerts.tsx
  frontend/src/app/billing/components/CurrentPlanDetails.tsx
  frontend/src/app/billing/page.tsx
  frontend/src/app/globals.css
  frontend/src/app/home/AppIntro.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/login/callback/page.tsx
  frontend/src/app/logout/callback/page.tsx
  frontend/src/app/page.tsx
  frontend/src/assets/icons/popular.svg
  frontend/src/assets/icons/tick.svg
  frontend/src/components/Header.tsx
  frontend/src/components/Pricing.tsx
  frontend/src/components/Profile.tsx
  frontend/src/components/ui/badge/badge.tsx
  frontend/src/components/ui/badge/index.ts
  frontend/src/constants/billing.ts
  frontend/src/constants/links.js
  frontend/src/hooks/useStripeCheckout.tsx
  frontend/src/services/billing.ts
  frontend/src/services/user.ts
  frontend/src/types/user.d.ts
  frontend/tailwind.config.ts
  requirements.txt
Labels: enhancement, Review effort [1-5]: 3, size:XXL

#155 Fix/main
  backend/config.py
  backend/routers/billing.py
Labels: size:XS

#156 better folder organization and logging
  .env.sample
  .gitignore
  backend/app_fastapi_v1.py
  backend/app_fastapi_v2.py
  backend/core/config.py
  backend/core/logger.py
  backend/db/connection.py
  backend/db/operations.py
  backend/kindle_auth.py
  backend/llm.py
  backend/middleware/check_auth.py
  backend/orchestrator.py
  backend/routers/billing.py
  tests_backend/e2e_test.py
  tests_backend/unittest/db/test_db_operations.py
Labels: size:L

#157 small fix
  requirements.txt
Labels: size:XS

#158 this isn't subscription but one time payment
  backend/routers/billing.py
Labels: size:XS
